dev-machine-recipe: allow config-only

diff --git a/bin/dev-machine-recipe b/bin/dev-machine-recipe
--- a/bin/dev-machine-recipe
+++ b/bin/dev-machine-recipe
@@ -64,255 +64,279 @@ elif [[ $(uname) == "Darwin" ]] ; then
   apple_p=true
 fi
 
+install_p=true
+config_p=true
+if [[ $1 == "config" ]] ; then
+  echo "## configuration only"
+  install_p=false
+fi
+
 kernel_release=$(uname -r)
 ossdir="${HOME}/code/oss"
 
-if $linux_p ; then
-  install="sudo apt-get install -y -q"
-  update="sudo apt-get update -q"
-  open="gnome-open"
-elif $apple_p ; then
-  install="brew install"
-  update="brew update"
-  open="open"
-  if [[ `which brew` == "" ]] ; then
-    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+if $install_p ; then
+  if $linux_p ; then
+    install="sudo apt-get install -y -q"
+    update="sudo apt-get update -q"
+    open="gnome-open"
+  elif $apple_p ; then
+    install="brew install"
+    update="brew update"
+    open="open"
+    if [[ `which brew` == "" ]] ; then
+      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+    fi
+  fi
+
+  #  update
+  ${update}
+
+  if $linux_p ; then
+    ${install} gnupg
+  elif $darwin_p ; then
+    ${install} gpg
+  fi
+
+  # rvm
+  if [[ `which rvm` == "" ]] ; then
+    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
+    curl -sSL https://get.rvm.io | bash -s stable
   fi
 fi
 
-#  update
-${update}
-
-if $linux_p ; then
-  ${install} gnupg
-elif $darwin_p ; then
-  ${install} gpg
-fi
-
-# rvm
-if [[ `which rvm` == "" ]] ; then
-  gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
-  curl -sSL https://get.rvm.io | bash -s stable
-fi
-
-if [[ `which bundle` != "" ]] ; then
-  bundle config jobs 2
+if $config_p ; then
+  if [[ `which bundle` != "" ]] ; then
+    bundle config jobs 2
+  fi
 fi
 
 if $linux_p ; then
-  #  basics for usability
-  ${install} \
-    gnome-do gnome-do-plugins \
-    gcolor2 \
-    keepassx \
-    msttcorefonts \
-    gconf-editor \
-    xclip \
-    kazam
+  if $install_p ; then
+    #  basics for usability
+    ${install} \
+      gnome-do gnome-do-plugins \
+      gcolor2 \
+      keepassx \
+      msttcorefonts \
+      gconf-editor \
+      xclip \
+      kazam
 
-  # if [[ `which google-chrome-beta` == "" ]] ; then
-  #     ${open} https://www.google.com/intl/en/chrome/browser/beta.html
-  # fi
+    # if [[ `which google-chrome-beta` == "" ]] ; then
+    #     ${open} https://www.google.com/intl/en/chrome/browser/beta.html
+    # fi
 
-  if [[ `which google-chrome-stable` == "" ]] ; then
-    ${open} https://www.google.com/intl/en/chrome/browser/desktop/index.html
-  fi
+    if [[ `which google-chrome-stable` == "" ]] ; then
+      ${open} https://www.google.com/intl/en/chrome/browser/desktop/index.html
+    fi
 
-  #  things I like for my desktop
-  ${install} \
-    terminator \
-    devilspie2 \
-    guake
+    #  things I like for my desktop
+    ${install} \
+      terminator \
+      devilspie2 \
+      guake
 
-  # music player -- instead install from source?
-  #     clementine \
+    # music player -- instead install from source?
+    #     clementine \
 
 
-  #  basics for development and related activities
-  ${install} \
-    git-core gitk subversion mercurial bzr \
-    direnv \
-    build-essential valgrind \
-    emacs24 autocutsel puppet-el \
-    markdown node-marked\
-    mariadb-server mariadb-client libmysqlclient-dev \
-    postgresql postgresql-client libpq-dev postgresql-contrib \
-    openjdk-8-jdk \
-    ack-grep \
-    curl wget \
-    cmake autoconf libtool \
-    libpcre++0v5 libpcre++-dev libevent-dev \
-    libssl-dev libcrypto++-dev \
-    libreadline-dev \
-    libxml2 libxml2-dev libxslt1.1 libxslt-dev \
-    libyajl-dev libyaml-dev \
-    colordiff \
-    zip
+    #  basics for development and related activities
+    ${install} \
+      git-core gitk subversion mercurial bzr \
+      direnv \
+      build-essential valgrind \
+      emacs24 autocutsel puppet-el \
+      markdown node-marked\
+      mariadb-server mariadb-client libmysqlclient-dev \
+      postgresql postgresql-client libpq-dev postgresql-contrib \
+      openjdk-8-jdk \
+      ack-grep \
+      curl wget \
+      cmake autoconf libtool \
+      libpcre++0v5 libpcre++-dev libevent-dev \
+      libssl-dev libcrypto++-dev \
+      libreadline-dev \
+      libxml2 libxml2-dev libxslt1.1 libxslt-dev \
+      libyajl-dev libyaml-dev \
+      colordiff \
+      zip
 
-  #  cf usage and development
-  if [[ `which cf` == "" ]] ; then
-    wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
-    echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
-    ${update}
-  fi
-  ${install} cf-cli
+    #  cf usage and development
+    if [[ `which cf` == "" ]] ; then
+      wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
+      echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
+      ${update}
+    fi
+    ${install} cf-cli
 
-  LPASSD="${ossdir}/lastpass-cli"
-  if [[ ! -d ${LPASSD} ]] ; then
-    pushd ${ossdir}
+    LPASSD="${ossdir}/lastpass-cli"
+    if [[ ! -d ${LPASSD} ]] ; then
+      pushd ${ossdir}
       git clone "https://github.com/lastpass/lastpass-cli"
-    popd
-  fi
-  if [[ `which lpass` == "" ]] ; then
-    pushd ${LPASSD}
-      make
-      sudo make install
-    popd
-  fi
-
-  #  less-basic stuff for LicenseFinder development
-  ${install} \
-    npm maven gradle rebar
-
-  if [[ ! -e /usr/bin/node ]] ; then
-    # https://github.com/joyent/node/issues/3911
-    echo "symlinking node -> nodejs"
-    sudo ln -s /usr/bin/nodejs /usr/bin/node
-  fi
-
-  if [[ `which bower` == "" ]] ; then
-    sudo npm install -g bower
-  fi
-
-  if [[ `which pip` == "" ]] ; then
-    ${install} python-pip python-dev
-    sudo pip install --upgrade pip
-    sudo pip install --upgrade virtualenv
-  fi
-
-  #  ugh, more esoteric stuff for libmagick
-  ${install} \
-    libmagickcore-dev libmagick++-dev
-
-  #  reading mac drives, encrypted drives, vpn, bootable drives, etc.
-  ${install} \
-    hfsprogs cryptsetup \
-    network-manager-openvpn-gnome \
-    gufw \
-    unetbootin
-
-  #  virtualbox
-  ${install} \
-    virtualbox-qt virtualbox-dkms \
-    nfs-common nfs-kernel-server
-
-  #if [[ `which vagrant` == "" ]] ; then
-  #  ${open} https://www.vagrantup.com/downloads.html
-  #fi
-
-  # #  dnsmasq
-  # ${install} dnsmasq
-
-  #  skype - download from https://www.skype.com
-  # ${install} \
-  #   skype ia32-libs
-
-  #  miscellaneous
-  ${install} \
-    htop \
-    remmina remmina-plugin-rdp libfreerdp-plugins-standard
-
-  #  .XCompose unicode input
-  XCOMPOSEDIR="${ossdir}/xcompose"
-  if [[ ! -d ${XCOMPOSEDIR} ]] ; then
-    pushd ${ossdir}
-      git clone "https://github.com/kragen/xcompose"
-    popd
-  fi
-  if [[ ! -e ${HOME}/.XCompose ]] ; then
-    pushd ${XCOMPOSEDIR}
-      ./install
-    popd
-  fi
-  ${install} uim
-
-  # heroku toolbelt
-  if [[ `which heroku` == "" ]] ; then
-    wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
-  fi
-
-  # flux
-  if [[ `which fluxgui` == "" ]] ; then
-    # Install dependencies
-    ${install} python-appindicator python-xdg python-pexpect python-gconf python-gtk2 python-glade2 libxxf86vm1
-
-    FLUXD="${ossdir}/xflux-gui"
-    if [[ ! -d $FLUXD ]] ; then
-      pushd $(dirname $FLUXD)
-        git clone "https://github.com/xflux-gui/xflux-gui.git"
       popd
     fi
-    pushd $FLUXD
+    if [[ `which lpass` == "" ]] ; then
+      pushd ${LPASSD}
+      make
+      sudo make install
+      popd
+    fi
+
+    #  less-basic stuff for LicenseFinder development
+    ${install} \
+      npm maven gradle rebar
+
+    if [[ ! -e /usr/bin/node ]] ; then
+      # https://github.com/joyent/node/issues/3911
+      echo "symlinking node -> nodejs"
+      sudo ln -s /usr/bin/nodejs /usr/bin/node
+    fi
+
+    if [[ `which bower` == "" ]] ; then
+      sudo npm install -g bower
+    fi
+
+    if [[ `which pip` == "" ]] ; then
+      ${install} python-pip python-dev
+      sudo pip install --upgrade pip
+      sudo pip install --upgrade virtualenv
+    fi
+
+    #  ugh, more esoteric stuff for libmagick
+    ${install} \
+      libmagickcore-dev libmagick++-dev
+
+    #  reading mac drives, encrypted drives, vpn, bootable drives, etc.
+    ${install} \
+      hfsprogs cryptsetup \
+      network-manager-openvpn-gnome \
+      gufw \
+      unetbootin
+
+    #  virtualbox
+    ${install} \
+      virtualbox-qt virtualbox-dkms \
+      nfs-common nfs-kernel-server
+
+    #if [[ `which vagrant` == "" ]] ; then
+    #  ${open} https://www.vagrantup.com/downloads.html
+    #fi
+
+    # #  dnsmasq
+    # ${install} dnsmasq
+
+    #  skype - download from https://www.skype.com
+    # ${install} \
+    #   skype ia32-libs
+
+    #  miscellaneous
+    ${install} \
+      htop \
+      remmina remmina-plugin-rdp libfreerdp-plugins-standard
+
+    #  .XCompose unicode input
+    XCOMPOSEDIR="${ossdir}/xcompose"
+    if [[ ! -d ${XCOMPOSEDIR} ]] ; then
+      pushd ${ossdir}
+      git clone "https://github.com/kragen/xcompose"
+      popd
+    fi
+    if [[ ! -e ${HOME}/.XCompose ]] ; then
+      pushd ${XCOMPOSEDIR}
+      ./install
+      popd
+    fi
+    ${install} uim
+
+    # heroku toolbelt
+    if [[ `which heroku` == "" ]] ; then
+      wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
+    fi
+
+    # flux
+    if [[ `which fluxgui` == "" ]] ; then
+      # Install dependencies
+      ${install} python-appindicator python-xdg python-pexpect python-gconf python-gtk2 python-glade2 libxxf86vm1
+
+      FLUXD="${ossdir}/xflux-gui"
+      if [[ ! -d $FLUXD ]] ; then
+        pushd $(dirname $FLUXD)
+        git clone "https://github.com/xflux-gui/xflux-gui.git"
+        popd
+      fi
+      pushd $FLUXD
       python download-xflux.py
       sudo python setup.py install # install globally
       #python setup.py install --user # install in your home directory
       (fluxgui 2>&1 > /dev/null &)
-    popd
+      popd
+    fi
+
+    # dropbox
+    ${install} dropbox python-gpgme
+
+    # cinnamon system monitor
+    ${install} gir1.2-gtop-2.0
+
+    # docker
+    if [[ `which docker` == "" ]] ; then
+      echo "FAIL: install docker, please"
+      ${open} https://docs.docker.com/engine/installation/ubuntulinux/
+      exit 1
+    else
+      echo "checking that docker was installed correctly ..."
+      docker run hello-world
+
+      ## only necessary if home is a separate partition from root or var
+      # echo "checking for alternate docker cache ..."
+      # if fgrep DOCKER_OPTS /etc/default/docker | fgrep -e "-g" ; then
+      #   echo "docker cache is OK!"
+      # else
+      #   echo "FAIL: docker is using the default cache directory"
+      #   echo "FAIL: edit /etc/default/docker to set '-g /home/docker' in DOCKER_OPTS"
+      #   ${open} https://forums.docker.com/t/how-do-i-change-the-docker-image-installation-directory/1169
+      #   exit 1
+      # fi
+    fi
+
+    #
+    #  power management
+    #  http://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html
+    #  http://linrunner.de/en/tlp/docs/tlp-configuration.html#rdw
+    #  TODO: make sure touchscreen is added to USB_WHITELIST in /etc/default/tlp
+    #
+    ${install} tlp tlp-rdw acpi-call-dkms smartmontools # linux-tools
+    # ${install} tp-smapi-dkms # fails to compile on 4.10.0 kernel
+
+    #
+    #  system debugging tools
+    #
+    ${install} linux-tools-common \
+               linux-tools-generic linux-tools-${kernel_release} \
+               wireshark \
+               sysdig
+
+    # go stuff, see https://johnsogg.github.io/emacs-golang
+    if [[ "$GOPATH" != "" ]] ; then
+      go get -u golang.org/x/tools/cmd/...
+      go get -u github.com/rogpeppe/godef/...
+      go get -u github.com/nsf/gocode
+      go get -u golang.org/x/tools/cmd/goimports
+      go get -u golang.org/x/tools/cmd/guru
+      go get -u github.com/dougm/goflymake
+    fi
   fi
 
-  # dropbox
-  ${install} dropbox python-gpgme
+  if $config_p ; then
+    #
+    # lenovo thinkpad section
+    #
+    if inxi -M | egrep "X2[0-9]0" 2>&1 > /dev/null ; then # x250/x230
 
-  # cinnamon system monitor
-  ${install} gir1.2-gtop-2.0
-
-  # docker
-  if [[ `which docker` == "" ]] ; then
-    echo "FAIL: install docker, please"
-    ${open} https://docs.docker.com/engine/installation/ubuntulinux/
-    exit 1
-  else
-    echo "checking that docker was installed correctly ..."
-    docker run hello-world
-
-    ## only necessary if home is a separate partition from root or var
-    # echo "checking for alternate docker cache ..."
-    # if fgrep DOCKER_OPTS /etc/default/docker | fgrep -e "-g" ; then
-    #   echo "docker cache is OK!"
-    # else
-    #   echo "FAIL: docker is using the default cache directory"
-    #   echo "FAIL: edit /etc/default/docker to set '-g /home/docker' in DOCKER_OPTS"
-    #   ${open} https://forums.docker.com/t/how-do-i-change-the-docker-image-installation-directory/1169
-    #   exit 1
-    # fi
-  fi
-
-  #
-  #  power management
-  #  http://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html
-  #  http://linrunner.de/en/tlp/docs/tlp-configuration.html#rdw
-  #  TODO: make sure touchscreen is added to USB_WHITELIST in /etc/default/tlp
-  #
-  ${install} tlp tlp-rdw acpi-call-dkms smartmontools # linux-tools
-  # ${install} tp-smapi-dkms # fails to compile on 4.10.0 kernel
-
-  #
-  #  system debugging tools
-  #
-  ${install} linux-tools-common \
-             linux-tools-generic linux-tools-${kernel_release} \
-             wireshark \
-             sysdig
-
-  #
-  # lenovo thinkpad section
-  #
-  if inxi -M | egrep "X2[0-9]0" 2>&1 > /dev/null ; then # x250/x230
-
-    # micmute - http://www.thinkwiki.org/wiki/Microphone_Mute_Button
-    if [[ ! -e /etc/acpi/lenovo-mutemic.sh ]] ; then
-      echo "CREATING: /etc/acpi/lenovo-mutemic.sh"
-      cat > /tmp/lenovo-mutemic.sh <<EOF
+      # micmute - http://www.thinkwiki.org/wiki/Microphone_Mute_Button
+      if [[ ! -e /etc/acpi/lenovo-mutemic.sh ]] ; then
+        echo "CREATING: /etc/acpi/lenovo-mutemic.sh"
+        cat > /tmp/lenovo-mutemic.sh <<EOF
 #!/bin/bash
 
 if [[ \$(amixer sget Capture) == *"[on]"* ]]; then
@@ -321,50 +345,42 @@ else
   amixer sset Capture cap
 fi
 EOF
-      chmod +x /tmp/lenovo-mutemic.sh
-      sudo mv /tmp/lenovo-mutemic.sh /etc/acpi
-    fi
+        chmod +x /tmp/lenovo-mutemic.sh
+        sudo mv /tmp/lenovo-mutemic.sh /etc/acpi
+      fi
 
-    if [[ ! -e /etc/acpi/events/lenovo-mutemic ]] ; then
-      echo "CREATING: /etc/acpi/lenovo-mutemic"
-      cat > /tmp/lenovo-mutemic <<EOF
+      if [[ ! -e /etc/acpi/events/lenovo-mutemic ]] ; then
+        echo "CREATING: /etc/acpi/lenovo-mutemic"
+        cat > /tmp/lenovo-mutemic <<EOF
 event=button/prog1 PROG1 00000080 00000000 K
 action=/etc/acpi/lenovo-mutemic.sh
 EOF
-      sudo mv /tmp/lenovo-mutemic /etc/acpi/events
-      sudo service acpid restart
-    fi
+        sudo mv /tmp/lenovo-mutemic /etc/acpi/events
+        sudo service acpid restart
+      fi
 
-  fi # x250/x230
+    fi # x250/x230
 
-  # lenovo usb keyboard section
+    # lenovo usb keyboard section
 
-  echo "checking for an external thinkpad keyboard ..."
-  for TPKB in "ThinkPad Compact USB Keyboard" "ThinkPad Compact Bluetooth Keyboard with TrackPoint" ; do
-    if xinput list | egrep "${TPKB}.*pointer" ; then
-      kbid=$(xinput list | egrep "${TPKB}.*pointer" | cut -f2 | cut -d= -f2)
-      echo "disabling middle-click paste ..."
-      xinput set-button-map ${kbid} 1 0 3
-    fi
-  done
+    echo "checking for an external thinkpad keyboard ..."
+    for TPKB in "ThinkPad Compact USB Keyboard" "ThinkPad Compact Bluetooth Keyboard with TrackPoint" ; do
+      if xinput list | egrep "${TPKB}.*pointer" ; then
+        kbid=$(xinput list | egrep "${TPKB}.*pointer" | cut -f2 | cut -d= -f2)
+        echo "disabling middle-click paste ..."
+        xinput set-button-map ${kbid} 1 0 3
+      fi
+    done
 
-  # fingerprint stuff
-  # if [[ `which fingerprint-gui` == "" ]] ; then
-  #   ${open} https://launchpad.net/~fingerprint/+archive/ubuntu/fingerprint-gui
-  # fi
-  
-  # cinnamon
-  gsettings set org.cinnamon number-workspaces 3
-fi
+    # fingerprint stuff
+    # if [[ `which fingerprint-gui` == "" ]] ; then
+    #   ${open} https://launchpad.net/~fingerprint/+archive/ubuntu/fingerprint-gui
+    # fi
 
-# go stuff, see https://johnsogg.github.io/emacs-golang
-if [[ "$GOPATH" != "" ]] ; then
-  go get -u golang.org/x/tools/cmd/...
-  go get -u github.com/rogpeppe/godef/...
-  go get -u github.com/nsf/gocode
-  go get -u golang.org/x/tools/cmd/goimports
-  go get -u golang.org/x/tools/cmd/guru
-  go get -u github.com/dougm/goflymake
+    # cinnamon
+    gsettings set org.cinnamon number-workspaces 3
+
+  fi
 fi
 
 set +o xtrace
